FROM openwms/org.openwms.common.service:latest
ARG JAR_FILE=target/openwms-wms-putaway.jar
ARG JAVA_OPTS="-Xshareclasses -Xquickstart -noverify"
COPY ${JAR_FILE} BOOT-INF/lib/openwms-wms-putaway.jar
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher", "${JAVA_OPTS}"]